export const TOGGLE_LIGHT_MODE = "TOGGLE_LIGHT_MODE";

export const WEBSITES_START = "WEBSITESS_START";
export const WEBSITES_ERROR = "WEBSITESS_ERROR";

// export const GET_SINGLE_PROJECTS_START = "GET_SINGLE_PROJECTS_START";
// export const ADD_PROJECT_START = "ADD_PROJECT_START";

export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_SINGLE_PROJECTS_SUCCESS = "GET_SINGLE_PROJECTS_SUCCESS";
export const ADD_PROJECT_SUCCESS = "ADD_PROJECT_SUCCESS";
export const SEND_EMAIL_SUCCESS = "SEND_EMAIL_SUCCESS";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";

// export const GET_SINGLE_PROJECTS_ERROR = "GET_SINGLE_PROJECTS_ERROR";
// export const ADD_PROJECT_ERROR = "ADD_PROJECT_ERROR";

export const SEND_EMAIL_ERROR = "SEND_EMAIL_ERROR";

// export const DELETE_PROJECT_ERROR = "DELETE_PROJECT_ERROR";

export const LOGO_START = "LOGO_START";
export const LOGO_ERROR = "LOGO_ERROR";
export const ADD_LOGO_SUCCESS = "ADD_LOGO_SUCCESS";
export const GET_LOGO_SUCCESS = "GET_LOGO_SUCCESS";
export const GET_SINGLE_LOGO_SUCCESS = "GET_SINGLE_LOGO_SUCCESS";
export const DELETE_LOGO_SUCCESS = "DELETE_LOGO_SUCCESS";

export const GRAPHIC_START = "GRAPHIC_START";
export const GRAPHIC_ERROR = "GRAPHIC_ERROR";
export const ADD_GRAPHIC_SUCCESS = "ADD_GRAPHIC_SUCCESS";
export const GET_GRAPHIC_SUCCESS = "GET_GRAPHIC_SUCCESS";
export const GET_SINGLE_GRAPHIC_SUCCESS = "GET_SINGLE_GRAPHIC_SUCCESS";
export const DELETE_GRAPHIC_SUCCESS = "DELETE_GRAPHIC_SUCCESS";

export const USER_START = "USER_START";
export const USER_ERROR = "USER_ERROR";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
