export const TOGGLE_LIGHT_MODE = "TOGGLE_LIGHT_MODE";

// Websites
export const WEBSITE_START = "WEBSITE_START";
export const WEBSITE_ERROR = "WEBSITE_ERROR";
export const GET_WEBSITES_SUCCESS = "GET_WEBSITES_SUCCESS";
export const GET_SINGLE_WEBSITE_SUCCESS = "GET_SINGLE_WEBSITE_SUCCESS";
export const ADD_WEBSITE_SUCCESS = "ADD_WEBSITE_SUCCESS";
export const DELETE_WEBSITE_SUCCESS = "DELETE_WEBSITE_SUCCESS";
// End of Websites

// Apps
export const APP_START = "APP_START";
export const APP_ERROR = "APP_ERROR";
export const GET_APPS_SUCCESS = "GET_APPS_SUCCESS";
export const GET_SINGLE_APP_SUCCESS = "GET_SINGLE_APP_SUCCESS";
export const ADD_APP_SUCCESS = "ADD_APP_SUCCESS";
export const DELETE_APP_SUCCESS = "DELETE_APP_SUCCESS";
// End of Apps

// export const GET_SINGLE_PROJECTS_ERROR = "GET_SINGLE_PROJECTS_ERROR";
// export const ADD_PROJECT_ERROR = "ADD_PROJECT_ERROR";

export const SEND_EMAIL_ERROR = "SEND_EMAIL_ERROR";
export const SEND_EMAIL_SUCCESS = "SEND_EMAIL_SUCCESS";

// export const DELETE_PROJECT_ERROR = "DELETE_PROJECT_ERROR";

export const LOGO_START = "LOGO_START";
export const LOGO_ERROR = "LOGO_ERROR";
export const ADD_LOGO_SUCCESS = "ADD_LOGO_SUCCESS";
export const GET_LOGO_SUCCESS = "GET_LOGO_SUCCESS";
export const GET_SINGLE_LOGO_SUCCESS = "GET_SINGLE_LOGO_SUCCESS";
export const DELETE_LOGO_SUCCESS = "DELETE_LOGO_SUCCESS";

export const GRAPHIC_START = "GRAPHIC_START";
export const GRAPHIC_ERROR = "GRAPHIC_ERROR";
export const ADD_GRAPHIC_SUCCESS = "ADD_GRAPHIC_SUCCESS";
export const GET_GRAPHIC_SUCCESS = "GET_GRAPHIC_SUCCESS";
export const GET_SINGLE_GRAPHIC_SUCCESS = "GET_SINGLE_GRAPHIC_SUCCESS";
export const DELETE_GRAPHIC_SUCCESS = "DELETE_GRAPHIC_SUCCESS";

export const USER_START = "USER_START";
export const USER_ERROR = "USER_ERROR";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
